// Occupations.ts

export enum Occupation {
  Carpenter = 'Carpenter',
  Electrician = 'Electrician',
  Painter = 'Painter',
  Mechanic = 'Mechanic',
  Chef = 'Chef',
  Developer = 'Developer',
  Designer = 'Designer',
  Writer = 'Writer',
  Doctor = 'Doctor',
  Teacher = 'Teacher',
  Plumber = 'Plumber',
  Engineer = 'Engineer',
  Artist = 'Artist',
  Photographer = 'Photographer',
  Accountant = 'Accountant',
  Lawyer = 'Lawyer',
  Nurse = 'Nurse',
  Architect = 'Architect',
  Scientist = 'Scientist',
  Librarian = 'Librarian',
  Pilot = 'Pilot',
  Farmer = 'Farmer',
  PoliceOfficer = 'Police Officer',
  Firefighter = 'Firefighter',
  Salesperson = 'Salesperson',
  Barista = 'Barista',
  Musician = 'Musician',
  Athlete = 'Athlete',
}
